// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkeJ6-R9V7Efb51asmP4nEuzyp9nab83I',
    appId: '1:1041997514539:web:0056858b2f1daefa17e76e',
    messagingSenderId: '1041997514539',
    projectId: 'authsignin-c1fbc',
    authDomain: 'authsignin-c1fbc.firebaseapp.com',
    storageBucket: 'authsignin-c1fbc.firebasestorage.app',
    measurementId: 'G-J1QTYJ4L68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ltLmAbIEfnERZ0b-PxkfpKUTiOGPfDY',
    appId: '1:1041997514539:android:02c8aec86c580f9d17e76e',
    messagingSenderId: '1041997514539',
    projectId: 'authsignin-c1fbc',
    storageBucket: 'authsignin-c1fbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEjSLoDRPUs_H3f5FqcsXRQ-31_Rkp9gk',
    appId: '1:1041997514539:ios:3266304e7f7e102317e76e',
    messagingSenderId: '1041997514539',
    projectId: 'authsignin-c1fbc',
    storageBucket: 'authsignin-c1fbc.firebasestorage.app',
    iosBundleId: 'com.example.habitrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkeJ6-R9V7Efb51asmP4nEuzyp9nab83I',
    appId: '1:1041997514539:web:c7fa438fdbd685eb17e76e',
    messagingSenderId: '1041997514539',
    projectId: 'authsignin-c1fbc',
    authDomain: 'authsignin-c1fbc.firebaseapp.com',
    storageBucket: 'authsignin-c1fbc.firebasestorage.app',
    measurementId: 'G-17L6W10L1L',
  );
}
